## <span style="color:blue">Problem Set 4</span>

**Note:**   
1. You need to use code to arrive at a solution.  Hardcoding a solution results in 0 points for the problem.
2. **Use only syntax covered in the Units so far.**  Using any other syntax results in 0 points for the problem.

### <span style="color:red">Run this cell first</span>

In [68]:
umSchools = {
  "A. Alfred Taubman College of Architecture & Urban Planning": 1906,
  "College of Engineering": 1854,
  "College of Literature, Science, and the Arts": 1841,
  "Gerald R. Ford School of Public Policy": 1914,
  "Horace H. Rackham School of Graduate Studies": 1912,
  "Penny W. Stamps School of Art & Design": 1974,
  "School of Dentistry": 1875,
  "School of Education": 1921,
  "School of Information": 1996,
  "School of Kinesiology": 1984,
  "School of Law": 1859,
  "School of Medicine": 1850,
  "School of Music, Theatre & Dance": 1880,
  "School of Natural Resources & Environment": 1927,
  "School of Nursing": 1893,
  "School of Pharmacy": 1876,
  "School of Public Health": 1941,
  "School of Social Work": 1951,
  "Stephen M. Ross School of Business": 1924
}

janTemps = """2016,   6, 51
        2015,  -3, 41
        2014, -14, 43
        2013,  -3, 60
        2012,   2, 55
        2011,   1, 52
        2010,   3, 47
        2009, -10, 39
        2008,   3, 62
        2007,   5, 50
        2006,  18, 53
        2005,  -3, 56
        2004,  -6, 55
        2003,  -5, 47
        2002,  11, 55
        2001,   1, 43
        2000,  -2, 56"""

 ### Problem 1
The dictionary _courses_ is a hypothetical schedule for a semester.  The key is the course code and the value is the number of credits. Print the course code along with the number of credits as shown in expected out. Also, use an accumulation pattern to find the total number of credits taken this semester and assign it to the variable _credits_. Print the variable _credits_ as shown below.

Do the following:
1. Iterate over courses:
   1.  Print the course code and credits.
   2.  Accumulate the credits in the variable _credits_.
2. Print the total credits

In [148]:
courses = {'CPS141':4, 'ENG101':3, 'CIS100':3, 'CNT206':4, 'MTH160':4}
# write your code below
credits=0
for course in courses:
    print(course, courses[course])
    credits+=int(courses[course])
print("Total credits this semester:", credits)

CPS141 4
ENG101 3
CIS100 3
CNT206 4
MTH160 4
Total credits this semester: 18


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
CPS141 4<br/>
ENG101 3<br/>
CIS100 3<br/>
CNT206 4<br/>
MTH160 4<br/>
Total credits this semester 18</span>

### Problem 2
The dictionary _umSchools_ maps the names of schools at Michigan to the year they were founded. Write code that creates a dictionary called _oldSchools_ that has the key/value pairs from _umSchools_ that correspond to the schools listed in the list _schools_ below.

Do the following:
1. Iterate over schools:
   1. Create a new dictionary using the current school as the key and the corresponding value from umSchools
2. Print _oldSchools_

In [19]:
schools = [ "College of Engineering","School of Nursing","School of Dentistry"]
# write your code below
oldSchools={}
for school in schools:
    oldSchools[school]=umSchools[school]
    
print(oldSchools)

{'College of Engineering': 1854, 'School of Nursing': 1893, 'School of Dentistry': 1875}


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
{'College of Engineering': 1854, 'School of Nursing': 1893, 'School of Dentistry': 1875}</span>

### Problem 3
Using the _umSchools_ dictionary, write code to add the name of every school that was founded in the 20th century (after 1900) into a list _newerSchools_. Print the list *newerSchools* as shown below.

In [23]:
newerSchools={}
for schools in umSchools:
    if(umSchools[schools]>=1900):
        newerSchools[schools]=umSchools[schools]
for schools in newerSchools:
    print(schools, "was founded in the 20th century.")

A. Alfred Taubman College of Architecture & Urban Planning was founded in the 20th century
Gerald R. Ford School of Public Policy was founded in the 20th century
Horace H. Rackham School of Graduate Studies was founded in the 20th century
Penny W. Stamps School of Art & Design was founded in the 20th century
School of Education was founded in the 20th century
School of Information was founded in the 20th century
School of Kinesiology was founded in the 20th century
School of Natural Resources & Environment was founded in the 20th century
School of Public Health was founded in the 20th century
School of Social Work was founded in the 20th century
Stephen M. Ross School of Business was founded in the 20th century


<span style="color:blue">Expected output:</span><br />
The required output is shown below but only the first three schools are shown to conserve space.  There are a total of 11 schools that meet this criterion.<br/>
<br />
<span style="font: courier; font-size: 13px">
A. Alfred Taubman College of Architecture & Urban Planning was founded in the 20th century.<br />
Gerald R. Ford School of Public Policy was founded in the 20th century.<br />
Horace H. Rackham School of Graduate Studies was founded in the 20th century</span>

### Problem 4
Given the string _paragraph_ below, write code to determine the most common word in the string and assign it to the variable _commonWord_, assign the frequency to _maxWordCount_.  The is a case insensitive frequency which means that case must be disregarded.

There are two parts:
1. The first part requires a loop that builds a dictionary of words and their frequency.
2. The second part requires a max accumulation pattern to find the word with the largest count.

A) Do the following to build the frequency dictionary:
1. Split the paragraph into words and store in a variable.
2. Initialize an empty dictionary
3. Iterate over the variable:
   1. You need to remove punctuation from the word.  
      If the last character in the word is a ".", ",", or a ";":
         1. Remove the last character in the word
   2. Convert the word to lowercase.
   3. If the word is in the dictionary:
         1. Increment the value associated with the word.  
   4. Otherwise:
         1. Initialize a new key using the word and assign 1 to the value

B) Determine the word with the largest frequency:
1. Iterate over the keys dictionary created in part A.
   1. if the value associated with current key is greater than _maxWordCount_:
      1. Store the current key in _commonWord_.
      2. Store the value of the current key in _maxWordCount_.

C) Print
1. Print _commonWord_ and _maxWordCount_ as shown below. 

Punctuation in the sentence must be removed as your code processes the word. You will also need to lower case the word.  You need to use the **split**, the **in** operator, and the **lower** function.

In [55]:
paragraph = """
He was getting  old and paunchy and his hair was falling fast,
And he sat around the Legion, telling stories of the past.
Of a war that he had fought in and the deeds that he had done,
In his exploits with his buddies; they were heroes, every one.
"""
# write your code below
maxWordCount=0
commonWord=''
paragraphSplit=paragraph.split("\n")
paragraphString=""
wordFrequency={}
for word in paragraphSplit:
    paragraphString+=word 
paragraphSplit=paragraphString.split(" ") #Question: it counts "fast,And", "past.Of" etc as one word. How to handle this?
for item in paragraphSplit:
    item=item.lower()
    for char in item:
        if char==',' or char=='.' or char==';':
            item=item[0:item.index(char)]
    if item not in wordFrequency:
        wordFrequency[item]=1
    else:
        wordFrequency[item]+=1
for wrd in wordFrequency:
    if wordFrequency[wrd]>maxWordCount:
        maxWordCount=wordFrequency[wrd]
        commonWord=wrd
        
print(commonWord, "is the most common word with", maxWordCount,"occurances")

he is the most common word with 4 occurances


<span style="color:blue">Expected output:</span><br />
<span style="font: courier; font-size: 13px">
he is the most common word with 4 occurances</span>

### Problem 5
Given the string _poem_ below, write code to determine the most common letter in the string and assign that to the variable _mostCommon_.  Also, assign the frequency of the most common letter to the variable _maxLetterCount_.  This is a case insensitive frequency which means lowercase and uppercase letters represent a single letter.

This problem is almost identical to problem 4 with the exception that you iterate over a string.  You should be able to make minor modifications to the code from problem 4 to achieve a solution.  Note, you need to skip spaces and punctuation.

Print _mostCommon_ and _maxLetterCount_ as shown below.

In [66]:
# A poem by Robert Frost
poem = """
Whose woods these are I think I know.
His house is in the village though;
He will not see me stopping here
To watch his woods fill up with snow.
My little horse must think it queer
To stop without a farmhouse near
Between the woods and frozen lake
The darkest evening of the year.
He gives his harness bells a shake
To ask if there is some mistake.
The only other sound’s the sweep
Of easy wind and downy flake.
The woods are lovely, dark and deep,
But I have promises to keep,
And miles to go before I sleep,
And miles to go before I sleep.
"""
# write your code below
poemSplit=poem.split("\n")
poemString=""
mostCommon=''
maxLetterCount=0
letterFrequency={}
for words in poemSplit:
    poemString+=words+" "
for char in poemString:
    if char==',' or char=='.' or char==';' or char==" ":
        char=char
    else:
        if char not in letterFrequency:
            letterFrequency[char]=1
        else:
            letterFrequency[char]+=1
for letter in letterFrequency:
    if letterFrequency[letter]>maxLetterCount:
        maxLetterCount=letterFrequency[letter]
        mostCommon=letter
print(mostCommon, "is the most common letter with", maxLetterCount,"occurances")
         

e is the most common letter with 66 occurances


<span style="color:blue">Expected output:</span><br />
<span style="font: courier; font-size: 13px">
e is the most common letter with 66 occurances</span>

### Problem 6
Write code that creates the dictionary _vowelFrequency_ where the keys are the five vowels and the values are number of occurances of that vowel in the string _sentence_. Using the _vowelFrequencies_ dictionary and a max accumulation pattern determine the most common vowel and assign the result to the variable _commonVowel_.  Print the variable _commonVowel_ and the _vowelFrequency_ dictionary as shown below. 

The problem is similar to the previous problem.  The exception is that you need to select only vowels in the string sentence.

In [67]:
sentence = "singing in the rain and playing in the rain are two entirely different situations but both can be good fun"
vowels = ['a','e','i','o','u']
# write your code below
vowelFrequency={}
commonVowel=''
maxVowelCount=0
for char in sentence:
    if char not in vowels:
        char=char
    else:
        if char not in vowelFrequency:
            vowelFrequency[char]=1
        else:
            vowelFrequency[char]+=1
for vow in vowelFrequency:
    if vowelFrequency[vow]>maxVowelCount:
        maxVowelCount=vowelFrequency[vow]
        commonVowel=vow
print(vowelFrequency)
print("The most common vowel is", commonVowel)

{'i': 11, 'e': 8, 'a': 7, 'o': 5, 'u': 3}
The most common vowel is i


<span style="color:blue">Expected output:</span><br />
<span style="font: courier; font-size: 13px">
{'i': 11, 'e': 8, 'a': 7, 'o': 5, 'u': 3}<br />
The most common vowel is i</span>

### Problem 7
The string _janTemps_ contains January temperature information for Ann Arbor for the years 2016 to 2000. This string is formatted so that it consists of multiple lines.  Each line is composed of three “columns” separated by commas. 
1. Year.
2. Lowest temperature.
3. Highest temperature.

Write code that will create two dictionaries: _janLows_, which maps the year to the lowest temperature, and _janHighs_, which maps the year to the highest temperature. The key for each dictionary is the year and the values are the temperatures.

Each set of values in the string is separated by a new-line character.  You must use .split('\n') to split the lines of _janTemps_ into a list. This results in a list of strings where each string holds the three columns.  As you iterate over that list, split a given line using a "," into a list containing the three column values. Use int() to cast the year, low temperature, and high temperature to integers.

Print the variables _janLows_ and _janHighs_.

In [120]:
januaryTemps=janTemps.split("\n")
janHighs={}
janLows={}

for line in januaryTemps:
    lineList=line.split(',')
    newLineList=[]
    for item in lineList:
        item=item.strip()
        item=int(item)
        newLineList.append(item)
    janHighs[newLineList[0]]=newLineList[2]
    janLows[newLineList[0]]=newLineList[1]

print("January low temperatures:\n", janLows)
print("January high temperatures:\n", janHighs)

January low temperatures:
 {2016: 6, 2015: -3, 2014: -14, 2013: -3, 2012: 2, 2011: 1, 2010: 3, 2009: -10, 2008: 3, 2007: 5, 2006: 18, 2005: -3, 2004: -6, 2003: -5, 2002: 11, 2001: 1, 2000: -2}
January high temperatures:
 {2016: 51, 2015: 41, 2014: 43, 2013: 60, 2012: 55, 2011: 52, 2010: 47, 2009: 39, 2008: 62, 2007: 50, 2006: 53, 2005: 56, 2004: 55, 2003: 47, 2002: 55, 2001: 43, 2000: 56}


<span style="color:blue">Expected output:</span><br />
<span style="font: courier; font-size: 13px">
January low temperatures:<br />
{2016: 6, 2015: -3, 2014: -14, 2013: -3, 2012: 2, 2011: 1, 2010: 3, 2009: -10, 2008: 3, 2007: 5, 2006: 18, 2005: -3, 2004: -6, 2003: -5, 2002: 11, 2001: 1, 2000: -2}<br />
January high temperatatures:<br />
{2016: 51, 2015: 41, 2014: 43, 2013: 60, 2012: 55, 2011: 52, 2010: 47, 2009: 39, 2008: 62, 2007: 50, 2006: 53, 2005: 56, 2004: 55, 2003: 47, 2002: 55, 2001: 43, 2000: 56}</span>

### Problem 8
Again using he string _janTemps_, write code that will determine which year had the largest difference between the lowest and highest temperature. Store the year as an integer in the variable  _maxTempDiffYear_ and temperature difference is the variable _maxTempDiff_.  

You need use much of the code from the above problem to parse each line in janTemps into the three values: year, lowest temperature, and the highest temperature.  Write additional code that uses a max accumulation pattern to calculate the largest temperature difference and the year when that difference occured.

Print _maxTempDiffYear_  and _maxTempDiff_ as shown below.

In [130]:
maxTempDiffYear=0
maxTempDiff=0
for year in janHighs:
    tempDiff=janHighs[year]-janLows[year]
    if tempDiff>maxTempDiff:
        maxTempDiff=tempDiff
        maxTempDiffYear=year
print("In January of {} the difference betweeb high and low temperatures was {}".format(maxTempDiffYear,maxTempDiff))

In January of 2013 the difference betweeb high and low temperatures was 63


<span style="color:blue">Expected output:</span><br />
<span style="font: courier; font-size: 13px">
In January of 2013 the difference between high and low temperatures was 63</span>

### Problem 9
The text file **Unit04_wnvhumancases.txt** contains data on West Nile virus infections in the United States from 2006 through 2018. Each record (line) in the file has four columns(values) separated by a comma. Each column is described below.

    Column 1:  Year (reported)
    Column 2:  Week (week reported)
    Column 3:  County
    Column 4:  Cases (number of cases reported)

Process the file and use an accumulation pattern to provide a count of the number of records(lines) in the file in the variable _numRecs_ and the total number of cases in the variable _numCases_.  Make sure you close the file after processing the data.

Hint:  Since this is a text file each line is a string. You will need to split the line into a list of values. 

This file must be co-resident with you notebook, otherwise a "file not found" error is thrown.

Print the variables _numRecs_  and _numCases_ as shown below.

In [138]:
file=open("Unit04_wnvhumancases.txt","r")
numRecs=0
numCases=0
for line in file:
    numRecs+=1
    lineSplit=line.split(',')
    numCases+=int(lineSplit[-1])
print("Total number of records: {}".format(numRecs))
print("Total number of cases: {}".format(numCases))
file.close()

Total number of records: 1789
Total number of cases: 4993


<span style="color:blue">Expected output:</span><br />
Total number of records: 1789<br />
Total number of cases: 4993</span>

### Problem 10
The csv file Unit04_wnvhumancases.csv is identical to the text file used in the previous proble, with the exception that it contains a header line and all fields are delimited by double-quotes.  The column names are shown below.

    Column 1:  Year (reported)
    Column 2:  Week (week reported)
    Column 3:  County
    Column 4:  Cases (number of cases reported)

Use the csv module to process the file and use an accumulation pattern to provide a count of the number of records in the file in the variable _numRows_ and the total number of incidents, i.e., a total of Positive Cases, in the variable _numIncidents_.  

You also need to identify the county with the highest number of incidents in the variable _maxCounty_, the year that the highest number of incidents occurred  in the variable _maxCountyYear_, and the number of incidents in _maxCountyIncidents_.

Do the same as the above but for the minimum,  Store the results in _minCounty_, _minCountyYear_, and _minCountyIncidents_. 

Print the information as shown below.

In [145]:
with open("Unit04_wnvhumancases.csv","r")as wnvFile:
    content=wnvFile.readlines()
    numRows=0
    numIncidents=0
    maxCounty=''
    maxCountyYear=0
    maxCountyIncidents=0
    minCounty=''
    minCountyYear=0
    minCountyIncidents=999999
    for line in content[1:]:
        numRows+=1
        eachLine=line.split(',')
        numIncidents+=int(eachLine[3])
        if int(eachLine[3])>maxCountyIncidents:
            maxCountyIncidents=int(eachLine[3])
            maxCounty= eachLine[2]
            maxCountyYear=int(eachLine[0])
        if (int(eachLine[3]))<minCountyIncidents:
            minCountyIncidents=int(eachLine[3])
            minCounty= eachLine[2]
            minCountyYear=int(eachLine[0])
print("Total cases: {}".format(numRows))
print("Total incidents: {}".format(numIncidents))
print("The county with the largest number of cases is {}, with {} incidents reported in the year {}".format(maxCounty,maxCountyIncidents,maxCountyYear))
print("The county with the smallest number of cases is {}, with {} incidents reported in the year {}".format(minCounty,minCountyIncidents,minCountyYear))
file.close()


Total cases: 1789
Total incidents: 4993
The county with the largest number of cases is Los Angeles, with 40 incidents reported in the year 2017
The county with the smallest number of cases is Alameda, with 1 incidents reported in the year 2006


<span style="color:blue">Expected output:</span><br />
Total cases:              1789<br />
Total incidents:          4993<br />
The county with the largest number of cases is Los Angeles, with 40 incidents reported in the year 2017<br />
The county with the smallest number of cases is Alameda, with 1 incidents reported in the year 2006</span>

### <span style="color:dark green">Run the cells below to test your code</span>

In [146]:
import unittest

class PS04_01 (unittest.TestCase):
    def test_problem01(self):
        self.assertEqual(credits, 18)
class PS04_02 (unittest.TestCase):
    def test_problem02(self):
        self.assertEqual(oldSchools, {'College of Engineering': 1854, 'School of Nursing': 1893, 'School of Dentistry': 1875})
class PS04_03 (unittest.TestCase):
    def test_problem03(self):
        self.assertTrue(type(newerSchools) is list) 
        self.assertEqual(len(newerSchools), 11)
class PS04_04 (unittest.TestCase):
    def test_problem04(self):
        self.assertEqual(commonWord, 'he')
        self.assertEqual(maxWordCount, 4)
class PS04_05 (unittest.TestCase):
    def test_problem05(self):
        self.assertEqual(mostCommon, 'e')
        self.assertEqual(maxLetterCount, 66)        
class PS04_06 (unittest.TestCase):
    def test_problem06(self):
        self.assertEqual(commonVowel, 'i')
        self.assertEqual(vowelFrequency['i'], 11)
        self.assertEqual(vowelFrequency,{'i': 11, 'e': 8, 'a': 7, 'o': 5, 'u': 3})
class PS04_07 (unittest.TestCase):
    def test_problem07(self):
        self.assertTrue(type(janLows) is dict) 
        self.assertTrue(type(janHighs) is dict) 
        self.assertEqual(janLows[2016], 6)
        self.assertEqual(janHighs[2016], 51)
class PS04_08 (unittest.TestCase):
    def test_problem08(self):
        self.assertEqual(maxTempDiffYear, 2013)
        self.assertEqual(maxTempDiff, 63)
class PS04_09 (unittest.TestCase):
    def test_problem09(self):
        self.assertEqual(numRecs, 1789)
        self.assertEqual(numCases, 4993)
class PS04_10 (unittest.TestCase):
    def test_problem10(self):
        self.assertEqual(numRows, 1789)
        self.assertEqual(numIncidents, 4993)
        self.assertEqual(maxCounty, 'Los Angeles')
        self.assertEqual(maxCountyIncidents, 40)
        self.assertEqual(maxCountyYear, 2017)     

In [150]:
unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

test_problem01 (__main__.PS04_01) ... ok
test_problem02 (__main__.PS04_02) ... ERROR
test_problem03 (__main__.PS04_03) ... ERROR
test_problem04 (__main__.PS04_04) ... ok
test_problem05 (__main__.PS04_05) ... ok
test_problem06 (__main__.PS04_06) ... ok
test_problem07 (__main__.PS04_07) ... ok
test_problem08 (__main__.PS04_08) ... ok
test_problem09 (__main__.PS04_09) ... ok
test_problem10 (__main__.PS04_10) ... ok

ERROR: test_problem02 (__main__.PS04_02)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ipykernel_1655713/1704947993.py", line 8, in test_problem02
    self.assertEqual(oldSchools, {'College of Engineering': 1854, 'School of Nursing': 1893, 'School of Dentistry': 1875})
NameError: name 'oldSchools' is not defined

ERROR: test_problem03 (__main__.PS04_03)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ipykernel_1655713/1704947993.py", l