## <span style="color:blue">Problem Set 3</span>

**Note:**   
1. You need to use code to arrive at a solution.  Hardcoding a solution results in 0 points for the problem.
2. **Use only syntax covered in the Units so far.**  Using any other syntax results in 0 points for the problem. 

### Problem 1

In the cell below, write code that iterates over the string _myStr_ and does the following:
1. Print each character.
2. Count the number of characters and stores the result the variable _cntChars_.

Print the variable _myStr_ and _cntChars_ with an appropriate label as shown below in Expected Output.

In [56]:
myStr = "MICHIGAN"

# Write your code below.
cntChars=0
for char in myStr:
    print(char)
    cntChars+=1
print("The number of characters in", myStr, "is", cntChars)

M
I
C
H
I
G
A
N
The number of characters in MICHIGAN is 8


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
M<br/>
I<br/>
C<br/>
H<br/>
I<br/>
G<br/>
A<br/>
N<br />
The number of characters in MICHIGAN is 8</span>

### Problem 2

In the cell below write one loop that iterates over the list _mixedList_ and does the following:
1. Prints each element and the element type.
2. Count the number of elements and store the result in the variable _cntList_.

Print _cntList_ preceded by an appropriate label as shown below.

In [62]:
mixedList = ["hello", 2, 4, 6.0, 7.5, 234352354, "the end", "", 99]

# Write your code below.
cntList=0
for element in mixedList:
    print(element, type(element))
    cntList+=1
print("The number of elements in the list is", cntList)

hello <class 'str'>
2 <class 'int'>
4 <class 'int'>
6.0 <class 'float'>
7.5 <class 'float'>
234352354 <class 'int'>
the end <class 'str'>
 <class 'str'>
99 <class 'int'>
The number of elements in the list is 9


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
hello <class 'str'><br/>
2 < class 'int'><br/>
4 < class 'int'><br/>
6.0 < class 'float'><br/>
7.5 < class 'float'><br/>
234352354 < class 'int'><br/>
the end < class 'str'><br/>
 < class 'str'><br/>
99 < class 'int'><br />
The number of elements in the list is 9</span>

### Problem 3
Write code that iterates over to the string _sentence_ and does the following:
1. Count the number of characters using the variable _numChars_.
2. Count the number of vowels using the variable _numVowels_. A character is a vowel if it is a member of the tuple _vowels_. 

Print the variables _numChars_ and _numVowels_ preceded by appropriate labels as shown below. 

Do NOT use the **len** function to solve the problem.  You may use the **len** function on the string to confirm the your answer is correct. 

In [60]:
sentence = "The quick brown rhino jumped over the extremely lazy fox."
vowels = ('a','e','i','o','u')
# Write your code below.
numChars=0
numVowels=0
for char in sentence:
    numChars+=1
    for vow in vowels:
        if char==vow:
            numVowels+=1
print("The number of characters is", numChars)
print("The number of vowels is", numVowels)

The number of characters is 57
The number of vowels is 16


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The number of characters is  57<br />
The number of vowels is  16
</span>

### Problem 4

Write code in the cell below that does the following:
1. Create a list called _words_ from the words in the string _sentence_.
2. Iterate over _words_ 
    1. Create a list called _wordLens_ which contains the length of every element in _words_.
    2. Count the number of words in _words_ using the variable _numWords_.
    3. Print the word and the word length.
3. Print _numWords_ as shown in expected output. 
4. Print the list _wordLens_.

You need one loop to solve this problem.  You need to use the **len** and **split** functions.  

In [67]:
sentence = "The quick brown rhino jumped over the extremely lazy fox"

# Write your code below.
words=sentence.split()
numWords=0
wordLens=[]
for word in words:
    wordLens+=[(len(word))]
    numWords+=1
    print(word, len(word))
print("The number of words is", numWords)
print(wordLens)


The 3
quick 5
brown 5
rhino 5
jumped 6
over 4
the 3
extremely 9
lazy 4
fox 3
The number of words is 10
[3, 5, 5, 5, 6, 4, 3, 9, 4, 3]


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The 3<br/>
quick 5<br/>
brown 5<br/>
rhino 5<br/>
jumped 6<br/>
over 4<br/>
the 3<br/>
extremely 9<br/>
lazy 4<br/>
fox 3<br/>
Number of words is 10<br/>
[3, 5, 5, 5, 6, 4, 3, 9, 4, 3]</span>

### Problem 5

The string _addStr_ contains list of numbers separated by the plus sign. Write code that uses an accumulation pattern to take the sum of all numbers and assigns it to the variable _sumVal_.  Print the variable _sumVal_ prefixed by an appropriate label. 

You should use the **split** function to split by "+" and int() to cast to an integer.

In [69]:
addStr = "2+5+10+20+15+37"

# Write your code below.
sumVal=0
addInt=addStr.split("+")
for num in addInt:
    sumVal+=int(num)
print("The total of all numbers is", sumVal)

The total of all numbers is 89


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The total of all numbers is 89</span>

### Problem 6

The string _weekTemps_ contains a comma-separated list of fahrenheit temperatures.  Write code that does the following:
1.  Finds the minimum temperature and stores the result in _minTemp_.
2.  Computes the average temperature and assign it to the variable _avgTemp_. 
Do not hard code your answer.  This means that your code must compute both the total of all temperatures and the number of temperatures in _weekTemps_.

Do the following:
1.  Split the string on ',' and store the resultant list in a variable
2.  Iterate over that variable:
    1. Apply a count pattern to count the number of temps.
    2. Apply an accumulation pattern to total the temperature values.
    3. if the current temperature is smaller than _minTemp_:
       1. Replace the contents of _minTemp_ with the current temperature.
3.  Compute the average temperature and store the result in _avgTemp_.
4.  Print _avgTemp_ and _minTemp_ as shown in the expected output.

The average temperature is defined as the total of all temperatures divided by the number of temperatures. 

You need to use one loop to solve this problem. You need to use the **split** and **float** functions.  

In [66]:
weekTemps = "75.1,77.7,83.2,82.5,81.0,79.5,85.7"
# Write your code below.
weekTempsList=weekTemps.split(",")
total=0
count=0
minTemp=float(weekTempsList[0])
for temp in weekTempsList:
    temp=float(temp)
    total+=temp
    count+=1
    if temp<minTemp:
        temp=minTemp
avgTemp=total/count
print("The average temperature is", avgTemp)
print("The minimun temperature is", minTemp)

The average temperature is 80.67142857142858
The minimun temperature is 75.1


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The average temperature is 80.67142857142858<br/>
The minimum temperature is 75.1</span>

### Problem 7

The variable _rainfallMI_ is a string of comma-separated values.  Each value is the monthly average rainfall in inches for Michigan. Write code that does the following:
1. Compute the number of months that have more than 3 inches of rainfall. Store the result in the variable _numRainyMonths_. 
2. Compute the total rainfall for all months.  Store the result in the variable _totRainfall_. 
3. Find the maximum rainfail and store it in _maxRain_.

Do the following:
1.  Split the string on ',' and store the resultant list in a variable
2.  Iterate over that variable:
    1. Apply an accumulation pattern to total the rainfallstoring the result in _totRainfall_.
    2. if the rainfall for the month is more than 3 inches:
       1.  Apply a count pattern storing the result in _numRainyMonths_.
    3. If the rainfall is larger than _maxRain_:
       1.  Replace the contents of _maxRain_ with the current rainfall.
3.  Print the variables _numRainyMonths_, and _maxRain_ with the appropriate label as shown below.

In [17]:
rainfallMI = "1.65, 1.46, 2.05, 3.03, 3.35, 3.46, 2.83, 3.23, 3.5, 2.52, 2.8, 1.85"

# Write your code below.
rainfallMIList=rainfallMI.split(",")
maxRain=0
totRainfall=0
numRainyMonths=0
for rain in rainfallMIList:
    rain=float(rain)
    totRainfall+=rain
    if rain>3:
        numRainyMonths+=1
    if rain>maxRain:
        maxRain=rain
print("Number of months with more than 3 inches of rain: ", numRainyMonths)
print("Total rainfall for all months is", totRainfall)
print("The maximum rainfall is", maxRain)

Number of months with more than 3 inches of rain:  5
Total rainfall for all months is 31.73
The maximum rainfall is 3.5


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
Number of months with more than 3 inches of rain 5<br />
Total rainfall for all months is 31.73<br />
The maximum rainfall is 3.5</span>

### Problem 8

The variable _sentence_ stores a string of words. Write code that does the following:
1. Compute the number of words that begin and end with the same letter including one-letter words. Store the result in the variable _sameLetterCount_.
2. Compute that number of word that contain an "f" or a "k".  Store the result in the variable _fkCount_. 

Do the following:
1. Split the sentence into words storing the result in a variable.
2. Iterate over the variable:
   1. If the first character of the word is equal to the last letter of the word:
      1. Apply a count pattern using the variable _sameLetterCount_.
   2. If the word contains an "f" or a "k":
      1. Apply a count pattern using the variable _fkCount_.
3. Print the variables _sameLetterCount_ and _fkCount_ as shown below. 

You need to use the **split** method,  the **in** operator to test for the existence of an "f" or "k", the **or** operator to join the logical expressions when testing for the existence of the letters. 

In [20]:
sentence = "students flock to the arb for a variety of outdoor activities such as jogging and picnicking"

# write your code below
sentenceSplt=sentence.split(" ")
sameLetterCount=0
fkCount=0
for word in sentenceSplt:
    if word[0]==word[len(word)-1]:
        sameLetterCount+=1
    if "f" in word or "k" in word:
        fkCount+=1
print("The number of words that begin and end with the same letter is", sameLetterCount)
print("The number of words that contain f or  is", fkCount)
    

The number of words that begin and end with the same letter is 2
The number of words that contain f or  is 4


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The number of words that begin and end with the same letter is 2<br />
The number of words that contain f or k is 4</span>

### Problem 9

Write code that does the following:
1. Compute the number of words in variable _sentence_ that contain either an "p" or an "g". Store the result in the variable _numPorG_.  
2. Creates a string _strPorG_ composed of those words in _sentence_ that contain an "p" or "g". Each word in _strPorG_ must be separated by a comma.

Print the variables _numPorG_ and _strPorG_ as shown below.

Do not double-count words that contain both an p and an g. Use the **in** operator to test for existence. 

In [37]:
sentence = "python is a high level general purpose programming language that can be applied to many different classes of problems"

# write your code below
numPorG=0
strPorG=""
sentenceSplt=sentence.split(" ")
for word in sentenceSplt:
    if 'p'in word or 'g' in word:
        numPorG+=1
        strPorG+=word+','
        
print("Number of words containing p or g is", numPorG)
print("Those words are", strPorG)

Number of words containing p or g is 8
Those words are python,high,general,purpose,programming,language,applied,problems,


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
Number of words containing p or g is 8<br />
Those words are python,high,general,purpose,programming,language,applied,problems</span>

### Problem 10

The cell below has two corresponding lists.  The list _rainFallMI_ has the average rainfall foe each month.  Each element in the list months corresponds to the value in the list _rainfallMI_. 

Write code that iterates over the list _months_ that does the following:
1. Displays the elements in the list _months_ and _rainfallMI_ as a two column table as shown below.
2. Finds the month with the largest rainfall and stores the month name in the variable _maxMonth_ and the rainfall value in _maxRain_. 
3. Finds the month with the smallest rainfall and stores the month name in the variable _minMonth_ and the rainfall value in _minRain_. 
4. Total the rainfall for the year and store the result in _totRain_.
Print the information as shown in expected output.

The month must printed  left-justified and the rainfall right-justified.  You must use string formatting.

Since you can only iterate over one sequence at a time.  You need to manually index into the list _rainfallMI_ as you iterate over the first. Also, you must use only one for loop.

In [64]:
rainfallMI = ['1.65', ' 1.46', ' 2.05', ' 3.03', ' 3.35', ' 3.46', ' 2.83', ' 3.23',
               ' 3.5', ' 2.52', ' 2.8', ' 1.85']
months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

# Write your code below.
print("Mon Rainfall")
maxMonth=""
maxRain=0
minMonth=""
minRain=float(rainfallMI[0])
totRain=0
for month in range (len(months)):
    print("{:4}{:>.2f}".format(months[month], float(rainfallMI[month])))
    totRain+=float(rainfallMI[month])
    if float(rainfallMI[month])> maxRain:
        maxRain=float(rainfallMI[month])
        maxMonth=months[month]
    if float(rainfallMI[month])<minRain:
        minRain=float(rainfallMI[month])
        minMonth=months[month]
print("The month with the largest rain fall is {} with a rainfall of {:.2f}".format(maxMonth,maxRain))
print("The month with the lowest rain fall is {} with a rainfall of {:.2f}".format(minMonth,minRain))
print("The annual rainfall is {:.2f}".format(totRain))

Mon Rainfall
Jan 1.65
Feb 1.46
Mar 2.05
Apr 3.03
May 3.35
Jun 3.46
Jul 2.83
Aug 3.23
Sep 3.50
Oct 2.52
Nov 2.80
Dec 1.85
The month with the largest rain fall is Sep with a rainfall of 3.50
The month with the lowest rain fall is Feb with a rainfall of 1.46
The annual rainfall is 31.73


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
Mon Rainfall<br/>
Jan 1.65<br/>
Feb 1.46<br/>
Mar 2.05<br/>
Apr 3.03<br/>
May 3.35<br/>
Jun 3.46<br/>
Jul 2.83<br/>
Aug 3.23<br/>
Sep 3.50<br/>
Oct 2.52<br/>
Nov 2.80<br/>
Dec 1.85<br/>
The month with the largest rainfall is Sep with a rainfall of 3.50<br/>
The month with the lowest rainfall is Feb with a rainfall of 1.46<br/>
The annual rainfall is 31.73<br/></span>

### <span style="color:dark green">Run the cells below to test your code</span>

In [54]:
import unittest

class PS03_01 (unittest.TestCase):
    def test_problem01(self):
        self.assertEqual(cntChars, 8)
class PS03_02 (unittest.TestCase):
    def test_problem02(self):
        self.assertEqual(cntList, 9)
class PS03_03 (unittest.TestCase):
    def test_problem03(self):
        self.assertEqual(numChars, 57)
        self.assertEqual(numVowels, 16)
class PS03_04 (unittest.TestCase):
    def test_problem04(self):
        self.assertEqual(numWords, 10)
        self.assertEqual(sum(wordLens), 47)
class PS03_05 (unittest.TestCase):
    def test_problem05(self):
        self.assertEqual(sumVal, 89)
class PS03_06 (unittest.TestCase):
    def test_problem06(self):
        self.assertEqual(round(avgTemp), 81)
        self.assertEqual(minTemp, 75.1)
class PS03_07 (unittest.TestCase):
    def test_problem07(self):
        self.assertEqual(numRainyMonths, 5)
        self.assertEqual(round(totRainfall), 32)
        self.assertEqual(maxRain, 3.5)
class PS03_08 (unittest.TestCase):
    def test_problem08(self):
        self.assertEqual(sameLetterCount, 2)
        self.assertEqual(fkCount, 4)
class PS03_09 (unittest.TestCase):
    def test_problem09(self):
        self.assertEqual(numPorG, 8)
        self.assertEqual(len(strPorG.split(',')), 8)
class PS03_10 (unittest.TestCase):
    def test_problem10(self):
        self.assertEqual(maxRain, 3.50)
        self.assertEqual(maxMonth, 'Sep')
        self.assertEqual(minRain, 1.46)
        self.assertEqual(minMonth, 'Feb')
        self.assertEqual(totRain, 31.73)

In [70]:
unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

test_problem01 (__main__.PS03_01) ... ok
test_problem02 (__main__.PS03_02) ... ok
test_problem03 (__main__.PS03_03) ... ok
test_problem04 (__main__.PS03_04) ... ok
test_problem05 (__main__.PS03_05) ... ok
test_problem06 (__main__.PS03_06) ... ok
test_problem07 (__main__.PS03_07) ... ok
test_problem08 (__main__.PS03_08) ... ok
test_problem09 (__main__.PS03_09) ... FAIL
test_problem10 (__main__.PS03_10) ... ok

FAIL: test_problem09 (__main__.PS03_09)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ipykernel_1270827/2275572622.py", line 36, in test_problem09
    self.assertEqual(len(strPorG.split(',')), 8)
AssertionError: 9 != 8

----------------------------------------------------------------------
Ran 10 tests in 0.008s

FAILED (failures=1)
