## <span style="color:blue">Problem Set 12</span>

#### Note:  These problems require recursive solutions.  No points will be give for solutions that are not recursive.

### Problem 1
Write a recursive function called _power_ that does exponentiation. The function accepts two arguments: num and exp.  The function takes num and raises to the power exp.  The solution does not require any python functions, and obviously should not use the python exponentiation operator.

In [176]:
 # write your function below
def power(num, exp):
    if exp==0:
        return 1
    if exp>1:
        return num*power(num,exp-1)
    
    else:
        return num
        
   
# do not change the code below but you may add additional calls to the function
print("2 to the 8th power is",power(2,8))
print("2 to the 15th power is",power(2,15))

2 to the 8th power is 256
2 to the 15th power is 32768


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
2 to the 8th power is 256<br />
2 to the 15th power is 32768</span>   

### Problem 2
Write a recursive function called _reverseString_ that reverses a string passed as an argument. Do not use any python function to reverse the string.  The string must be reversed by your code.  The only python function required is len().  

In [175]:
 # write your function below
def reverse_string(string): 
    if len(string) == 0:
        return string
    else:
        return reverse_string(string[1:]) + string[0]
              
    
# do not change the code below but you may add additional calls to the function
string_to_reverse = "the quick brown fox jumps over the lazy dog"
print("The original string:",string_to_reverse)
print("The reversed string:",reverse_string(string_to_reverse))
print()
string_to_reverse = "able was I ere I saw elba"
print("The original string:",string_to_reverse)
print("The reversed string:",reverse_string(string_to_reverse))

The original string: the quick brown fox jumps over the lazy dog
The reversed string: god yzal eht revo spmuj xof nworb kciuq eht

The original string: able was I ere I saw elba
The reversed string: able was I ere I saw elba


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The original string: the quick brown fox jumps over the lazy dog<br />
The reversed string: god yzal eht revo spmuj xof nworb kciuq eht<br />
<br />
The original string: able was I ere I saw elba<br />
The reversed string: able was I ere I saw elba</span>   

### Problem 3
Write a recursive function called _reverseList_ that reverses a list passed as an argument. Do not use any python function to reverse the list.  The list must be reversed by your code.  The only python function required is len().  Hint:  The expression list1 + list2 is a new list consisting of list 2 appended to list 1.

In [91]:
 # write your function below
def reverse_list(lst):
    if len(lst)==0:
        return lst
    else:
        lst2=[lst[0]]
        lst=lst[1:]
        return reverse_list(lst)+lst2

# do not change the code below but you may add additional calls to the function
list_to_reverse = [1,2,3,4,5,6,7,8,9,0]
print("The original list:",list_to_reverse)
print("The reversed list:",reverse_list(list_to_reverse))

The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
The reversed list: [0, 9, 8, 7, 6, 5, 4, 3, 2, 1]


### Problem 4
Write a recursive function called _totalDigits_ that give a number _n_ returns the sum of the digits of _n_. Hint: you need to convert the number to a string in the function.

In [173]:
 # write your function below
def totalDigits(n):
    num=str(n)
    if len(num)==1:
        return int(num)
    else:
        smallerNum=int(num[0])
        num=num[1:]
        return smallerNum+totalDigits(num)
    
    
# do not change the code below but you may add additional calls to the function
for m in [111,222,333,1076458]:
    print("The total of the digits in",m,"is",totalDigits(m))

The total of the digits in 111 is 3
The total of the digits in 222 is 6
The total of the digits in 333 is 9
The total of the digits in 1076458 is 31


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
TThe total of the digits in 111 is 3<br/>
The total of the digits in 222 is 6<br/>
The total of the digits in 333 is 9<br/>
The total of the digits in 1076458 is 31</span>  

### Problem 5

Write a recursive function called **convertToDecimal** that accepts a binary number (string type) and converts it to decimal. Assume a valid binary number is passed so there is not need for error checking.  Also since the binary number passed is a string, you will need to coerce each digit into an integer using the int() function.  This function must work for any binary number of any length, so do not hard code position values.  Position values must be calculated by the function.

The value of the positions for binary numbers are:

    2**n  2**(n-1) ... 2**3  2**2  2**1  2**0   where 2**0 is 1

Determining the decimal value of a binary number:
  1. For each digit, multiply the digit by the value of the position
  2. Repeat step one for all digits in the binary number
  3. Add all the results together
  


In [164]:
 # write your function below
def convertToDecimal(binary):
    binary=str(binary)
    if len(binary)==1:
        if binary[0]=="0":
            return 0
        else:
            return 1
    else:
        position=len(binary)-1
        indexZero=int(binary[0])
        binary=binary[1:]
        math=0
        if indexZero==1:
            math=2**position
            return math+int(convertToDecimal(binary))
        else:
            return convertToDecimal(binary)
        
bin = '11111111'
print("The binary number",bin,"is",convertToDecimal(bin),"in decimal")
bin = '10101010'
print("The binary number",bin,"is",convertToDecimal(bin),"in decimal")

The binary number 11111111 is 255 in decimal
The binary number 10101010 is 170 in decimal
