## <span style="color:blue">Problem Set 8</span>

### <span style="color:red">Run the cell below first</span>
Before starting the assignment, run the cell below.  

In [1]:
# do all our imports at the top of the file, because that's the standard style
import csv
import json
import requests
from Unit08_vincenty import latLngDistanceMeters

fh = open('Unit08_umich_buildings.json','r')
umich_buildins_str = fh.read()
umich_buildings = json.loads(umich_buildins_str) 


baby_file = open('Unit08_us-common-baby-names.csv','r')
baby_reader = csv.DictReader(baby_file)
baby_names = list(baby_reader) # turn the reader object into a real list


The variable *umich_buildings* is list where each element is a dictionary.  The keys in the dictionary contained in each list element are: 

<table>
  <tr>
    <th style="text-align: center">Key</th>
    <th style="text-align: center">Description</th> 
  </tr>
  <tr>
    <td style="text-align: center">address</td>
    <td  style="text-align: left">The address of the building</td> 
  </tr>
  <tr>
    <td style="text-align: center">id</td>
    <td  style="text-align: left">The building id, e.g.,asb is Administrative Services Building </td> 
  </tr>
  <tr>
    <td style="text-align: center">lat</td>
    <td  style="text-align: left">The geographic latitude,i.e., north-south position of a point on the Earth's surface</td> 
  </tr>
  <tr>
    <td style="text-align: center">lng</td>
    <td  style="text-align: left">The geographic longitude,i.e.,the angular distance of a place east or west of the meridian at Greenwich, England</td> 
  </tr>
  <tr>
    <td style="text-align: center">name</td>
    <td  style="text-align: left">The building name</td> 
  </tr>
</table>

Below is typical element in the list:  
{  
&nbsp;&nbsp;&nbsp;&nbsp;"address": "1201 South Main Street Ann Arbor, MI 48104-3722",  
&nbsp;&nbsp;&nbsp;&nbsp;"id": "stadm",  
&nbsp;&nbsp;&nbsp;&nbsp;"lat": 42.265071,  
&nbsp;&nbsp;&nbsp;&nbsp;"lng": -83.748662,  
&nbsp;&nbsp;&nbsp;&nbsp;"name": "Michigan Stadium"  
}  

### Problem 1
Write a function named *buildingLatLong* that returns a (name,latitude, longitude) tuple for any building id in *umich_buildings*. You will need to iterate over umich_buildings, then for each list element compare the value associated with the id key to the value passed to the function. If that building id could not be found, return *None*.

Write code that iterates of *bldgs* and prints the output below.

In [3]:
bldgs = ['ccrb','aep','taubl','unknown','nq','stadm']

        
# write your code below
def buildingLatLong(buildingid):
    for building in umich_buildings:
        if buildingid==building['id']:
            infoTuple=(building['name'],building['lat'],building['lng'])
            return infoTuple
for item in bldgs:
    print(buildingLatLong(item))

('Central Campus Recreation Building', 42.278866, -83.732666)
('Aerospace Engineering Lab Plasma Research', 42.293342, -83.710823)
('Alfred A Taubman Health Sciences Library', 42.28358, -83.734543)
None
('North Quadrangle', 42.280477, -83.740131)
('Michigan Stadium', 42.265071, -83.748662)


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
('Central Campus Recreation Building', 42.278866, -83.732666)<br/>
('Aerospace Engineering Lab Plasma Research', 42.293342, -83.710823)<br/>
('Alfred A Taubman Health Sciences Library', 42.28358, -83.734543)<br/>
None<br/>
('North Quadrangle', 42.280477, -83.740131)<br/>
('Michigan Stadium', 42.265071, -83.748662</span>

### Problem 2
"Vincenty's formulas are two related iterative methods used to calculate the distance between two points on the surface of a spheroid, developed by Thaddeus Vincenty (1975a)"

The file *Unit08_vincenty.py*, which was imported in the first cell, contains code that calculates the "vincenty distance" between two points' using the latitude and longitude of both points. The function *latLngDistanceMeter*, present in vincenty.py, accepts two tuples as parameters where each tuple contains the coordinates (latitude,longitude) of a point on the Earth and performs the vincenty calculation.  Below is an example of how this function is called:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;latLngDistanceMeters((42.3584, -71.0912), (42.278, -83.7382))

Write a function named *buildingDistance* that is passed two building IDs and determines the vincenty distance between two building IDs.

Write code that iterates over the *bldgs* list, *buildingDistance* for each tuple in the list, and prints the output below.

In [4]:
bldgs = [('ccrb','aep'),('taubl','nq')]

# write your code below
def buildingDistance(id1,id2):
    bld1=buildingLatLong(id1)
    bld2=buildingLatLong(id2)
    return latLngDistanceMeters((bld1[1],bld1[2]),(bld2[1],bld2[2]))
    

for items in bldgs:
    
    print("The vincenty distance between building", items[0], "and ", items[1]," is", buildingDistance(*items))

The vincenty distance between building ccrb and  aep  is 2414.804664314132
The vincenty distance between building taubl and  nq  is 575.5430991021018


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The vincenty distance between building ccrb and aep is 2414.804664314132<br />
The vincenty distance between building taubl and nq is 575.5430991021018</span>

### Problem 3: 
Write code that iterates over _umich_buildings_ and outputs a _.csv_ file called _north_quad_distance.csv_. 

The csv file has two columns: 

1. The building name.
2. The vincenty distance of that building from North Quad(nq).

Since this is a csv file the first row in the file is a header that identifies the two columns.  Column 1 of the first row has the value "Name" and column 2 has the value "Distance from NQ". There should be one subsequent row for each building (including North Quad, which should have a zero distance).  You should use the string .format() function to format each row in the csv file.

Check your work by opening the .csv file in a text editor or importing it into a spreadsheet program like Excel or Google Sheets.

You file should appear similar to that below:  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name,Distance from NQ  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1000 Victors Way,4674.366005  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1032 Greene Building,1498.650608  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;523 South Division Building,639.5818755  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Administrative Services Building,1410.470849  

In [37]:
outfile=open("north_quad_distance", "w")
outfile.write("Distance from North Quad")
outfile.write("\n")
outfile.write("Name, Distance from NQ")
outfile.write("\n")
for buildingNQ in umich_buildings:
    if buildingNQ['id']=="nq":
        nq=(buildingNQ)
for building in umich_buildings:
    vincentyD=buildingDistance(building['id'],nq['id'])
    row_string='{},{}'.format(building['name'],vincentyD)
    outfile.write(row_string)
    outfile.write("\n")


### Problem 4
This next problem uses the list _baby_names_ loaded from Unit08_us-common-baby-names.csv (see first cell). Each element in the list is an OrderedDict object which is just like a dictionary except the elements are ordered in creation sequence.  This means that you may treat _baby_names_ as a list where each element in the list is a dictionary.  A sample row appears as below.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OrderedDict([('year', '1880'),('name', 'John'),('percent', '0.081541'),('sex', 'boy')])
             
In the above, what appears as tuples are actually key/value pairs with the first element of the tuple being the key and the second element the value . The _percent_ key holds a percentage value which represents the number of babies born that year who were given the name found in the value of the _name_ key.  For example:  if the current line is in the variable _row_, the expression _row['year']_ references the year value and the expression _row['name']_ references the baby name. 

Write the function _popularInYear_ that accepts the  parameter _year_ and returns the most popular name for that year and the associated percent. The most popular name is the one with the largest percentage.  This problem is essentially finding the maximum percentage in the _baby_names_ list that matches the _year_ parameter.  

Write code the iterates over _years_ list and prints the most popular name for each year as shown below.

In [66]:
years = ['1900','1925','1950','1975','2000']

# write your code below
#take year
#return most popular baby name of that year
#iterate through all name entries with that year
#find the entry with the largest percentage
#return the name that has the largest percentage of the year specified
def popularInYear(year):
    popName=""
    popPerc=0
    for row in baby_names:
        yearBaby=str(row['year'])
        if year==yearBaby:
            percent=float(row['percent'])
            if percent>popPerc:
                popPerc=percent
                popName=row['name']
    return popName
def popPercent(year):
    popName=""
    popPerc=0
    for row in baby_names:
        yearBaby=str(row['year'])
        if year==yearBaby:
            percent=float(row['percent'])
            if percent>popPerc:
                popPerc=percent*100
                popName=row['name']
    return popPerc
for year in years:
    print("Most popular name in {} is {} with {:.2f} percent".format(year, popularInYear(year),popPercent(year)))



Most popular name in 1900 is John with 6.06 percent
Most popular name in 1925 is Mary with 5.59 percent
Most popular name in 1950 is James with 4.73 percent
Most popular name in 1975 is Michael with 4.22 percent
Most popular name in 2000 is Jacob with 1.65 percent


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
Most popular name in 1900 is John with 6.06 percent<br/>
Most popular name in 1925 is Mary with 5.59 percent<br/>
Most popular name in 1950 is James with 4.73 percent<br/>
Most popular name in 1975 is Michael with 4.22 percent<br/>
Most popular name in 2000 is Jacob with 1.65 percent</span>

### Nested Data and Nested Iteration
Many web services return information either in a json or xml format.  Below is sample json return by the Facebook API and is representative in structure of the json returned by most web services.  You will be working complex nested data in future modules.  This problem will serve as a warmup for those future problem sets.

First, just get familiar with the structure of the data. You may want to copy and paste it to a site like https://jsoneditoronline.org/ so you may inspect the data.

### <span style="color:red">Run the cell below before completing the problems that follow.</span>

In [67]:
fb_data = {
 "data": [
  {
    "id": "2253324325325123432madeup", 
    "from": {
      "id": "23243152523425madeup", 
      "name": "Jane Smith"
    }, 
    "to": {
      "data": [
        {
          "name": "Your Facebook Group", 
          "id": "432542543635453245madeup"
        }
      ]
    }, 
    "message": "This problem might use the accumulation pattern, like many problems do", 
    "type": "status", 
    "created_time": "2014-10-03T02:07:19+0000", 
    "updated_time": "2014-10-03T02:07:19+0000"
  }, 
 
  {
    "id": "2359739457974250975madeup", 
    "from": {
      "id": "4363684063madeup", 
      "name": "John Smythe"
    }, 
    "to": {
      "data": [
        {
          "name": "Your Facebook Group", 
          "id": "432542543635453245madeup"
        }
      ]
    }, 
    "message": "Here is a fun link about programming", 
    "type": "status", 
    "created_time": "2014-10-02T20:12:28+0000", 
    "updated_time": "2014-10-02T20:12:28+0000"
  }]
}

### Problem 5
Extract the contents of the first message into a variable called *first_message*.  Print *first_message*.

In [109]:
json_string=json.dumps(fb_data)
json_dict=json.loads(json_string)

string2=json.dumps(json_dict['data'])
dict2=json.loads(string2)

messageD=dict(dict2[0])
first_message=messageD['message']
print(first_message)

This problem might use the accumulation pattern, like many problems do


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
This problem might use the accumulation pattern, like many problems do</span>

### Problem 6
Extract the name of the author of the second post, into a variable called *second_name*.  Print *second_name*.

In [112]:
message2=dict(dict2[1])
from2=message2['from']
second_name=from2['name']
print(second_name)

John Smythe


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
John Smythe</span>

### Problem 7
Write code that generates a list of the names of all the authors of the messages in fb_data. Store it in a variable called _authors_.  Print the variable _authors_.

<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
['Jane Smith', 'John Smythe']</span>

### <span style="color:red">Run the cell below before completing the problems that follow.</span>

In [113]:
zipCodeData = [
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Alpena",
            "longitude": "-83.4602",
            "post code": "49707",
            "latitude": "45.079"
         }
      ],
      "country": "United States",
      "place name": "Alpena",
      "state": "Michigan",
      "state abbreviation": "MI"
   },
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Hubbard Lake",
            "longitude": "-83.6059",
            "post code": "49747",
            "latitude": "44.8947"
         }
      ],
      "country": "United States",
      "place name": "Hubbard Lake",
      "state": "Michigan",
      "state abbreviation": "MI"
   },
   {
      "country abbreviation": "US",
      "places": [
         {
            "place name": "Suttons Bay",
            "longitude": "-85.6423",
            "post code": "49682",
            "latitude": "44.9656"
         }
      ],
      "country": "United States",
      "place name": "Suttons Bay",
      "state": "Michigan",
      "state abbreviation": "MI"
   }
]

### Problem 8
Write code that iterates over the zipCodeData list and prints the nested _places_ list where the _place name_ (first-level place name) has a value of Hubbard Lake. 

In [128]:
for dictionary in zipCodeData:
    for places in dictionary['places']:
        if places['place name']=='Hubbard Lake':
            print(places)
            

{'place name': 'Hubbard Lake', 'longitude': '-83.6059', 'post code': '49747', 'latitude': '44.8947'}


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
{'place name': 'Hubbard Lake', 'longitude': '-83.6059', 'post code': '49747', 'latitude': '44.8947'}]</span>

### Problem 9
Write a function called _getZipData_ that accepts a _post code_ (zip code) as an argument and returns a tuple containing the associated _place name_, _longitude_, and _latitude_ for _zipCodeData_.  If the _post code_ passed to the function is not in the zipCodeData list, the returned tuple should have a value of None, 0, and 0 for the _place name_, _latitude_, and _longitude_ respectively.

Do the following in the function:
1. Initialize variables as necessary.
2. Iterate over _zipCodeData_: 
   1. Iterate over nexted _places_ list:
      1. If _post code_ in the current place is equal to the _post code_ passed:
         1. Store the _place name, _longitude_, and _latitude in the variables
3. Return the variables as a tuple

In [191]:
# write your function below
def getZipData(postcode):
    lng=0
    lat=0
    found=False
    for dictionary in zipCodeData:
        for places in dictionary['places']:
                if places['post code']==str(postcode):
                    found=True
                    lng=places['longitude']
                    lat=places['latitude']
                    placeTuple=(places['place name'], lng , lat)
                    return placeTuple
    if found==False:
        noneTuple=('None',0,0)
        return noneTuple

# Do not change the code below
for zipcode in ['49682','49707','11111']:
     print(getZipData(zipcode))


('Suttons Bay', '-85.6423', '44.9656')
('Alpena', '-83.4602', '45.079')
('None', 0, 0)


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
('Suttons Bay', '-85.6423', '44.9656')<br />
('Alpena', '-83.4602', '45.079')<br />
(None, 0, 0)</span>

### Problem 10
Using the functions getZipData and latLngDistanceMeters write code that calculates the vincenty distance in kilometers between zip codes 49707 and 49747.  Print the output __exactly__ as shown below.  

The latLngDistanceMeters returns the distance in meters.  To convert to kilometers, divide the retuned value by 1000.  

In [214]:
id1=getZipData(49707)
id2=getZipData(49747)
id1LatLng=(float(id1[1]),float(id1[2]))
id2LatLng=(float(id2[1]), float(id2[2]))
distance=latLngDistanceMeters(id1LatLng, id2LatLng)/1000
print(distance)
print("The vincenty distance between {} and {} is {:.2f}km".format(id1[0], id2[0],distance))

16.43604039472689
The vincenty distance between Alpena and Hubbard Lake is 16.44km


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The vincenty distance between Alpena and Hubbard Lake is 23.48km</span>